# Generated by Django 5.1.5 on 2025-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_global_places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="state_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
