__title__ = 'Django-GlobalPlaces'
__description__ = 'Django-GlobalPlaces is a Django app to provide models and helpers for working with places.'
__url__ = 'https://github.com/lucacitta/Django-GlobalPlaces'
__version__ = '0.8.7'
__author__ = '@lucacitta https://github.com/lucacitta'
__author_email__ = 'lucacitta.dev@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024 @lucacitta https://github.com/lucacitta'
